# Generated by Django 2.0.1 on 2018-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSiteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=30)),
                ('url_site', models.URLField()),
                ('url_search', models.URLField()),
                ('queryTermsDic', models.CharField(max_length=256)),
                ('soupTermsDic', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
                ('postcode', models.CharField(max_length=9)),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
