# Generated by Django 2.0.1 on 2018-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUAuctionSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsitedetails',
            name='url_search',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auctionsitedetails',
            name='url_site',
            field=models.CharField(max_length=30),
        ),
    ]
