# Generated by Django 2.0.1 on 2018-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUAuctionSearch', '0003_urlproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlproxy',
            name='httpProxy',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='urlproxy',
            name='httpsProxy',
            field=models.CharField(max_length=30),
        ),
    ]
